In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr)

[1 2 3 4 5 6 7]


### NumPy Creating Arrays


Create a NumPy ndarray Object

In [6]:

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array((1,2,3,4,5))

print(arr)



[1 2 3 4 5]


0 dimensi

In [8]:
import numpy as np
arr = np.array(42)
print(arr)

42


1 dimensi


In [9]:
import numpy as np
arr = np.array((1,2,3,4,5,6))

print ( arr)

[1 2 3 4 5 6]


2 dimensi

In [ ]:
import numpy as np

arr = np.array(((1,2,3,4),(2,3,4,5)))# bisa pake kurung () bisa juga pake []

print(arr)

[[1 2 3 4]
 [2 3 4 5]]


3 Dimensi

In [13]:
import numpy as np
arr = np.array(([1,2,3],[2,3,4],[3,4,5]))

print(arr)

[[1 2 3]
 [2 3 4]
 [3 4 5]]
